[package]
name = "szdat"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "szdat"
path = "src/bin/szdat.rs"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_cbor = "0.11.2"
